{
 "title": "Langchain4j",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "AI Services",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "langchain4j_aiservices_counted_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Token Usage Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gen_ai_client_token_usage_total{gen_ai_token_type=\"input\"}",
     "legendFormat": "{{service_name}} ( model: {{gen_ai_request_model}} )"
    }
   ]
  },
  {
   "title": "Output Token Usage Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gen_ai_client_token_usage_total{gen_ai_token_type=\"output\"}",
     "legendFormat": "{{service_name}} ( model: {{gen_ai_request_model}} )"
    }
   ]
  },
  {
   "title": "AI Estimated Cost Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "gen_ai_client_estimated_cost_total",
     "legendFormat": "{{service_name}} ( model: {{gen_ai_request_model}} )"
    }
   ]
  },
  {
   "title": "AI Client Operation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (service_name) (\r\n  rate(gen_ai_client_operation_duration_seconds_sum[5m])\r\n)\r\n/\r\nsum by (service_name) (\r\n   rate(gen_ai_client_operation_duration_seconds_count[5m])\r\n)",
     "legendFormat": "{{service_name}} (avg)"
    }
   ]
  },
  {
   "title": "AI Services Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (aiservice) (\r\n  rate(langchain4j_aiservices_timed_seconds_sum[5m])\r\n)\r\n/\r\nsum by (aiservice) (\r\n  rate(langchain4j_aiservices_timed_seconds_count[5m])\r\n)",
     "legendFormat": "{{aiservice}} (avg)"
    }
   ]
  }
 ]
}